import { EVENT_GET_LIST } from './actionTypes'

export function getEvents() {
    return {
        type: EVENT_GET_LIST,
        payload: [
            {
                id: '1',
                imageLink: 'https://s2.glbimg.com/hPZXUAStHS4R8PUIR0mEUhF_7Lk=/0x0:1846x1232/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2018/r/j/08PObBSlC4dxJzCLjctQ/roupa-nova.jpg',
                title: 'Rock in Rio',
                subTitle: 'O maior show de rock da América Latina',
                local: 'R. Manuel da Nóbrega, 1361 - Ibirapuera, São Paulo - SP, 04001-140',
                category: ['Música', 'Show de banda', 'Entretenimento'],
                description: 'Muse, Imagine Dragons e Nickelback no Rock in Rio 2019',
                price: '100',
                unsold: '19',
                duration: '90m',
                inicialDate: '19/09/2019',
                endDate: '',
                dateFormated: 'SET 19',
                responsibleEntity: 'Rock enterprise',
                subscribed: []
            },
            {
                id: '2',
                imageLink: 'https://www.unip.br/modulos/comunicacao/noticia/img_noticia/3820_22381.jpg',
                title: 'Carreira, Liderança e Startup',
                subTitle: 'Como mergulhar de vez no empreendedorismo',
                local: 'Av. Comendador Enzo Ferrari, 280 - Swift, Campinas - SP, 13045-770',
                category: ['', 'Politica'],
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla at risus. Quisque purus magna, auctor et, sagittis ac, posuere eu, lectus. Nam mattis, felis ut adipiscing.',
                price: '700',
                unsold: '20',
                duration: '60m',
                inicialDate: '15/11/2019',
                endDate: '',
                dateFormated: 'NOV 15',
                responsibleEntity: 'Unip - Universidade Paulista',
                subscribed: []
            },
            {
                id: '3',
                imageLink: 'https://s2.glbimg.com/owRzXuQNMwTCElFbzITcpgFe92U=/940x523/e.glbimg.com/og/ed/f/original/2018/04/26/architecture-auditorium-blue-382297.jpg',
                title: 'Jantar de gala da OAB de Campinas',
                subTitle: 'O evento é destinado aos profissionais de toda a demanda jurídica de Campinas',
                local: 'Rua Armando Strazzacappa - Fazenda Santa Cândida, Campinas - SP, 13092-599',
                category: ['Conferência'],
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla at risus. Quisque purus magna, auctor et, sagittis ac, posuere eu, lectus. Nam mattis, felis ut adipiscing.',
                price: '0',
                unsold: '503',
                duration: '120m',
                inicialDate: '15/11/2019',
                endDate: '',
                dateFormated: 'NOV 15',
                responsibleEntity: 'OAB Campinas',
                subscribed: []
            },
            {
                id: '4',
                imageLink: 'https://www.iwu.edu/tedx/tbankstedx.jpg',
                title: 'TED',
                subTitle: 'Tom Thum: A orquestra em minha boca',
                local: '317 Pitt St, Sydney NSW 2000, Austrália',
                category: ['Entretenimento', 'Música'],
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla at risus. Quisque purus magna, auctor et, sagittis ac, posuere eu, lectus. Nam mattis, felis ut adipiscing.',
                price: '30',
                unsold: '20',
                duration: '60m',
                inicialDate: '16/11/2019',
                endDate: '',
                dateFormated: 'NOV 16',
                responsibleEntity: 'TED TALKS',
                subscribed: []
            },
            {
                id: '5',
                imageLink: 'https://www.e-dublin.com.br/wp-content/uploads/2016/09/electric-picnic-723x370.jpg',
                title: 'Festa de ação de graças na comunidade evangélica de Nilópolis',
                subTitle: 'Rock in Rio',
                local: 'Umuarama',
                category: ['Entretenimento', 'Musica', 'Politica'],
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla at risus. Quisque purus magna, auctor et, sagittis ac, posuere eu, lectus. Nam mattis, felis ut adipiscing.',
                price: '700',
                unsold: '20',
                duration: '20m',
                inicialDate: '02/11/2019',
                endDate: '',
                dateFormated: 'NOV 02',
                responsibleEntity: 'Comunidade evangélica de Nilópolis',
                subscribed: []
            },
            {
                id: '6',
                imageLink: 'https://static1.squarespace.com/static/51ef2bf2e4b02bcf8471333b/51ef2bf2e4b02bcf8471333f/5a20813e0d9297f9736add18/1553524978187/oktoberfest-sp.jpg?format=1000w',
                title: '3ª São Paulo Oktoberfest ',
                subTitle: 'Muito mais que cerveja! É diversão, cultura, música, comida, amizade!',
                local: 'Av. Lineu de Paula Machado, 1263 - Cidade Jardim, São Paulo - SP, 05601-000',
                category: ['Entretenimento', 'Musica'],
                description: 'A Oktoberfest é um festival de cerveja originado em Munique, Alemanha. Venha curtir conosco!',
                price: '99',
                unsold: '57',
                duration: '300m',
                inicialDate: '26/09/2019',
                endDate: '',
                dateFormated: 'SET 26',
                responsibleEntity: 'Jockey Club',
                subscribed: []
            },
            {
                id: '7',
                imageLink: 'https://www3.al.sp.gov.br/repositorio/noticia/N-07-2018/fg226006.jpg',
                title: 'Doe Vida - Cadastramento de medula óssea',
                subTitle: 'Ação promovida por estudantes da Faculdade São Leopoldo Mandic.',
                local: 'Av. Dona Renata, 71 - Centro, Araras - SP, 13600-001',
                category: ['Academico', 'Educacional'],
                description: 'Grupo de estudantes promove uma ação, com o apoio da Liga Acadêmica Solidária e da Faculdade São Leopoldo Mandic – Unidade Araras, para cadastro de medula óssea. A finalidade é atualizar os bancos de doação e encontrar doadores compatíveis com os pacientes, e para isso basta doar 10 ml de sangue.',
                price: '0',
                unsold: '227',
                duration: '240m',
                inicialDate: '28/09/2019',
                endDate: '',
                dateFormated: 'SET 28',
                responsibleEntity: 'Faculdade São Leopoldo Mandic',
                subscribed: []
            },
            {
                id: '8',
                imageLink: 'https://scontent.fcpq2-1.fna.fbcdn.net/v/t1.0-9/69791304_702711653572268_7478670653801889792_o.jpg?_nc_cat=107&_nc_oc=AQm_l9SYIV8C8qG7t3umzCseD2QH2soPXKJ1sTp0fmk50ANJU5SNREUTWvkub5G5ScPwxqjzKr_EhPKVGlpRPzyE&_nc_ht=scontent.fcpq2-1.fna&oh=365a69d44de9da17ad22dc92e024a3c9&oe=5E35549E',
                title: 'VII Congresso de Jovens - Tu És Soberano',
                subTitle: 'A criação nos remete à glória do Criador;',
                local: 'Rua João Puche, 500, 13172-455 Sumaré',
                category: ['Espiritual', 'Conferencia'],
                description: ' criação nos remete à glória do Criador; Àquele que tem todo poder e domínio sobre todas as coisas; O Deus que tudo governa e que nEle tudo subsiste; Nele foram criadas todas as coisas; O Deus que perdoa pecados e purifica toda injustiça; O Deus que consola os cansados e oprimidos, cura os doentes e traz paz ao coração mesmo em meio ao sofrimento e angústia;',
                price: '0',
                unsold: '200',
                duration: '120m',
                inicialDate: '01/12/2019',
                endDate: '18/12/2019',
                dateFormated: 'JAN 30',
                responsibleEntity: 'Segunda Igreja Batista de Sumaré - SIBS',
                subscribed: []
            },
            {
                id: '9',
                imageLink: 'https://scontent.fcpq2-1.fna.fbcdn.net/v/t1.0-9/70837758_2697122850320217_6089522198408593408_o.jpg?_nc_cat=100&_nc_oc=AQn_0ptZohZNR4wZmQv_DuBdRN9vMh6qh6lNpjMj1MOZ-7YHfyg45gTAjuD6Iqxgq5yDvOuKjkrnBrQk95hBCXaL&_nc_ht=scontent.fcpq2-1.fna&oh=0fa18c5ac2c8bfe211c01c23cd65178e&oe=5E000489',
                title: '24º Campinas Anime Fest no Liceu Salesiano!',
                subTitle: 'Vem aí o maior evento Geek do interior paulista!',
                local: 'Rua Baronesa Geraldo de Resende, 330, 13.075-270 Campinas',
                category: ['Entretenimento', 'Feira', 'Conferencia'],
                description: 'São dezenas de convidados e diversas atrações em Quadrinhos, Games, Internet, Cosplay, Dublagem, Cinema, e muita cultura Pop!',
                price: '24',
                unsold: '185',
                duration: '300m',
                inicialDate: '01/12/2019',
                endDate: '',
                dateFormated: 'DEC 01',
                responsibleEntity: 'Circuito Anime Fest e Avalon Eventos',
                subscribed: []
            },
            {
                id: '10',
                imageLink: 'https://scontent.fcpq2-1.fna.fbcdn.net/v/t1.0-9/69709525_2321882894526140_19997668377886720_n.jpg?_nc_cat=105&_nc_oc=AQlDo1VinMY2pjCGubYg4w4vocShwcqClXHs5QHNX44jV1Q5NBIb6af_hRAW3K0rHhZ8tRsRyh-DHQEHLcXmCdoS&_nc_ht=scontent.fcpq2-1.fna&oh=4c9279a74192ab99d65dba9af48f034b&oe=5DFF5B89',
                title: '8° Edição Car Club Campinas Em Prol Da Aninha',
                subTitle: 'A Aninha tem um tipo de paralisia que afetou sua parte motora e desde o seu nascimento com sua irmãzinha gêmea Manu',
                local: 'Rua Dr Alcides Carvalho, 127, 13013-082 Campinas',
                category: ['Entretenimento'],
                description: 'A equipe CAR CLUB CAMPINAS irá fazer esse evento beneficente e toda a renda arrecadada será repassada a família, pra ajudar no seu tratamento!',
                price: '0',
                unsold: '150',
                duration: '420m',
                inicialDate: '01/12/2019',
                endDate: '',
                dateFormated: 'SEP 29',
                responsibleEntity: 'Car Club Campinas',
                subscribed: []
            },
            {
                id: '11',
                imageLink: 'https://www.casalucci.com.br/wp-content/uploads/2019/03/festas-1200x675.jpg',
                title: 'Kombate',
                subTitle: 'A festa vai ser pokasideias e muita lacração! Quem quiser aparecer traz um kit churrasco e a bebida',
                local: 'Rua Armando Strazzacappa, 130, 13024-021 Campinas',
                category: ['Entretenimento', 'Musica'],
                description: 'A FECAU vem em peso patrocinar o maior duelo de pop e funk que a UNICAMP já viu! O bailão vai pegar fogo!',
                price: '15',
                unsold: '30',
                duration: '1D',
                inicialDate: '29/09/2019',
                endDate: '',
                dateFormated: 'SET 29',
                responsibleEntity: 'FECAU',
                subscribed: []
            },
            {
                id: '12',
                imageLink: 'https://i0.wp.com/horrorexpo.com.br/wp-content/uploads/2018/08/atracoes-img.jpg?w=800&ssl=1',
                title: 'Horror Expo 2019',
                subTitle: 'Feira Internacional do Gênero Horror para Cinema, Tv, Literatura, Games, Música e Cultura Pop',
                local: 'Rua José Bernardo Pinto, 333 - Vila Guilherme, São Paulo - SP, 02055-000',
                category: ['Entretenimento', 'Musica'],
                description: 'A HORROR EXPO é uma feira que tem como objetivo reunir grandes nomes do gênero do Horror/Terror, nos campos do cinema, TV, séries, literatura, comics, videogames, serviços de streaming, música e cultura pop.',
                price: '180',
                unsold: '125',
                duration: '2d',
                inicialDate: '18/10/2019',
                endDate: '',
                dateFormated: 'OUT 18',
                responsibleEntity: 'VP Group',
                subscribed: []
            },
        ]
    }
}
